### ISSUE TITLE
Prevent submission of the form if no voice has been selected

### ISSUE THREAD

**Issue by markdturner** [ATNU/soundscapes-of-text-client#3]
Currently, the server throws an error if no voice is selected in the UI. This could be fixed by disabling the buttons until one has, or setting a default and pre-selecting it

**Comment by MattNolf** [comment]
Commit [77f0ae4b8cad71c6f141449af59fe046cfb4ad49](https://github.com/ATNU/soundscapes-of-text-client/commit/77f0ae4b8cad71c6f141449af59fe046cfb4ad49) should resolve this.

Emma is selected as default voice.
