### ISSUE TITLE
Sample voice audio not working

### ISSUE THREAD

**Issue by markdturner** [ATNU/soundscapes-of-text-client#4]
Requests to play samples for each of the voices return 404 resopnses

**Comment by MattNolf** [comment]
This is the result of the previous changes with ssml interpretation.
Modifying handlers:67 should resolve:
f, err := Generate(("<speak>Hi my name is " + mux.Vars(r)["id"] + "</speak>"), mux.Vars(r)["id"],
			path.Join(viper.GetString("assets.demoPath"), mux.Vars(r)["id"]), p)

**Comment by markdturner** [comment]
Turns out the bug was to do with not fully setting the server URL with the right port number rather than an SSML error. When I ran the code you suggest it said:

"speak Hi my name is Emma less than forward slash speak"

Setting it back to the original fixed that - once I remembered to clear the cached mp3 files
